### ISSUE TITLE
replace letsencrypt by certbot the new client

### ISSUE THREAD

**Issue by arthurzenika** [saltstack-formulas/letsencrypt-formula#29]
https://github.com/letsencrypt/letsencrypt redirects to https://github.com/certbot/certbot

**Comment by moebiuseye** [comment]
:+1:

**Comment by hackel** [comment]
Should this project be renamed?  Looks like someone already has a decent start at this:
https://github.com/livecirrus/certbot-formula

Edit: I merged her work with all the latest changes here:
https://github.com/hackel/certbot-formula
I'm hesitant to do a PR until it's decided that the everything should be renamed.

**Comment by arthurzenika** [comment]
I would say that keeping letencrypt in the name of the formula is not a bad idea since it is better known than certbot and make it more easy to find for people wanting to use letsencrypt. We could even imagine that one could choose in the pillars to use another client than certbot (there are litterally 100s)

**Comment by moebiuseye** [comment]
Why not do exactly what letsencrypt did and redirect saltstack-formulas/letsencrypt-formula to saltstask-formulas/certbot-formula ?

**Comment by hackel** [comment]
Since CertBot is a generic ACME protocol client, I do believe that this is what the formula should be referred to as.  It can be used with CAs other than Let'sEncrypt—hopefully even traditional/commercial CAs in the future.  Redirecting the repo to the new name seems like the right move to me.  People will get accustomed to the new terminology eventually.

**Comment by iggy** [comment]
Should there be some support for moving the old config directory? Otherwise it'll be hanging around for no reason. Alternatively, a warning so the user can go back and do something with it.

Have we verified whether we can get a redirect setup from letsencrypt-formula to certbot-formula? I do like the idea of making this formula as easy to find as possible to people that are looking for either name.

If we are good to go on both of those questions, I'm okay with the change.

**Comment by hackel** [comment]
The fork I linked to above (and which I'm now using) is actually still using /etc/letsencrypt, along with the {check,renew}_letsencrypt_cert.sh scripts.  Just to keep things extra confusing, apparently Certbot stlil uses the old config directory as a default:
https://certbot.eff.org/docs/using.html#configuration-file
Should the config directory be customizable in the pillar?
